### ISSUE TITLE
private post list for users

### ISSUE THREAD

**Issue by GenoTheMundane** [divSelector/divchan#12]
can you add a list of all the person's posts, but only one that they can view, so that they can edit or delete their own posts without having to look through the entire website?

**Comment by divSelector** [comment]
Yeah I think I'll do this once I've added the edit feature. No ETA but it will be done

**Comment by divSelector** [comment]
https://github.com/divSelector/divchan/commit/3278dfd0e335677b7ea66dc6c73f4e98e6161a21 done
