### ISSUE TITLE
(Enhancement) toggle which boards are available

### ISSUE THREAD

**Issue by GenoTheMundane** [divSelector/divchan#13]
Basically when there are enough hidden boards there should be a settings area where you can toggle them on and off to be available on the main page

**Comment by divSelector** [comment]
done 
![image](https://github.com/divSelector/divchan/assets/119910428/cc1852b5-29e2-4ab5-a077-4dbc467d31be)

https://github.com/divSelector/divchan/commit/80a3afbbfb2bef3f40a911b0190311ffb7acab33

And several fix commits after that one go with it.
